server:
  port: 8083

spring:
  application:
    name: competition-ms

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    loadbalancer:
      eager-load:
        enabled: true
        clients: utilisateur-ms

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:root@localhost:27017/competition_db?authSource=admin}

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 10s
  circuitbreaker:
    instances:
      utilisateur-ms:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
