server:
  port: 8083

spring:
  application:
    name: competition-ms

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:root@localhost:27017/competition_db?authSource=admin}