server:
  port: 8082

spring:
  application:
    name: cours-ms

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3308/cours_db}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      utilisateur-ms:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
