server:
  port: 8084

spring:
  application:
    name: badge-ms

  datasource:
    url: jdbc:mysql://localhost:3306/badge_db
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true