server:
  port: 8083

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:root@localhost:27017/competition_db?authSource=admin}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      utilisateur-ms:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s